name: Build and Deploy Vlocity Components to Dev Org

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1

      - name: Install Vlocity
        run: npm install -g vlocity

      - name: Build project
        run: npm run build

  deploy:
    needs: build
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenSSL
        run: sudo apt-get install -y openssl

      - name: Generate server.key
        run: |
          openssl genrsa -out server.key 2048
          openssl req -new -key server.key -out server.csr -subj "/CN=Salesforce"
          openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
          cat server.key

      - name: Set JWT environment variable
        run: echo "JWT_SECRET=$JWT_SECRET" >> $GITHUB_ENV
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Salesforce CLI
        if: always()
        run: |
          if ! command -v sfdx &> /dev/null; then
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
            sudo ./sfdx/install
          fi
        env:
          SFDX_AUTOUPDATE_DISABLE: true

      - name: Authenticate with Salesforce Dev Org
        env:
          SFDX_LOGIN_URL: https://login.salesforce.com/
          SFDX_USERNAME: sam.nathan3699@devops.com
          SFDX_CLIENT_ID: 3MVG9JJwBBbcN47LO.vTT_CuU2g_gOobvkFW3lcm5J9OhnKThVjeErP8nFpqlUBHxU4E6zhW86Kv.MLKY.XPE
          SFDX_CLIENT_SECRET: 6Cel800Dak000002ErMl888ak00000025ur4jIfzL90LirG8A6WrzdodLI3s7CGXJ66BntooLh64jRlLIVly92lhpOddyGwTGCFgwJp8q30
          SFDX_AUTH_JWT_KEY: ${{ env.JWT_SECRET }}
        run: |
          sfdx auth:jwt:grant --clientid $SFDX_CLIENT_ID --jwtkeyfile server.key --username $SFDX_USERNAME --setdefaultdevhubusername --setalias my-dev-org --instanceurl $SFDX_LOGIN_URL

      - name: Deploy Vlocity Components
        env:
          SFDX_PACKAGE_PATH: 'path/to/your/vlocity/package'
        run: |
          sfdx force:source:deploy --sourcepath $SFDX_PACKAGE_PATH --targetusername my-dev-org
