name: Salesforce JWT Auth

on:
  push:
    branches:
      - main

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli

      - name: Authenticate with Salesforce using JWT
        run: |
          sf org login jwt --client-id PlatformCLI --jwt-key-file server.key --username kumar@sentara.sandbox --instance-url https://bermtecinc-dev-ed.develop.my.salesforce.com --set-default-dev-hub --alias vscodeOrg
